### ISSUE TITLE
Issue implementing multiselect in angular 9, text values in the dropdown list are empty.

### ISSUE THREAD

**Issue by cattlleya** [ngx-lib/multiselect#113] opened 2020-07-28 07:52 UTC
Hi, i just noticed when implementing multiselect in angular 9, text values in the dropdown list are empty
<img width="183" alt="multiselect issue" src="https://user-images.githubusercontent.com/46396056/88635499-4b271a80-d0ea-11ea-9a8b-687d4d8ab407.PNG">
 (only text values are empty).

**Comment by cattlleya** [comment] 2020-07-28 08:12
As work around, i used the ng template for binding "  <ng-template let-option="option">"

**Comment by pankajparkar** [comment] 2020-07-29 01:28
@cattlleya Hey thanks for reporting an issue 🙏

I've tried reproducing this issue with Angular version 9, I was not able to reproduce it.

Here is a working stackblitz link. Can you please check this stackblitz here and try to reproduce this issue here?

I suspect in your case either text color of the dropdown is inherited as white from parent CSS or there may be some other issue (check browser console and add that screenshot here).

**Comment by cattlleya** [comment] 2020-07-29 06:06
Hi @pankajparkar , i wanna share these codes below. 

--component.ts
  this.searchTypes = [
            { id: 1, name: "Records"},
            { id: 2, name: "Profile" },
            { id: 3, name: "Access" }
        ];
		

this.selectedSearchType = [{
            id: 1,
            name: "Records"
        }];		
	
<ngx-multiselect
    [(ngModel)]="selectedSearchType"
    [options]="searchTypes"
    ngDefaultControl>
</ngx-multiselect>	


My Work Around Fix:
<ngx-multiselect
    [(ngModel)]="selectedSearchType"
    [options]="searchTypes"
    ngDefaultControl>
	<ng-template let-option="option">
          <span> 
                {{option.name}}
           </span>
   </ng-template>
</ngx-multiselect>	


And also attached here the browser console screenshot which is i think not related in css theme. 
<img width="1082" alt="multiselect issue 2" src="https://user-images.githubusercontent.com/46396056/88762817-7ec67b00-d1a4-11ea-8264-68f5a8e87ffa.png">

**Comment by pankajparkar** [comment] 2020-07-29 07:29
@cattlleya Can you please mention which angular version your using?
Snapshot of `ng -v` command and `package.json` dependencies and `devDependencies` snapshot.

**Comment by pankajparkar** [comment] 2020-07-29 07:34
@cattlleya I quickly tried to updated the stackblitz with the code that you provided.

https://stackblitz.com/edit/ngx-multilselect-xxdn1w?file=src%2Fapp%2Fapp.component.html

Would you mind to check and let me know if I missed anything in there?

**Comment by pankajparkar** [comment] 2020-07-31 02:17
@cattlleya I can able to reproduce this issue. I'll work on fixing this. Here something from me within couple of days.

**Comment by cattlleya** [comment] 2020-07-31 12:45
> @cattlleya I can able to reproduce this issue. I'll work on fixing this. I'll get back to you within a couple of days with solution.

Hi @pankajparkar , thanks for the update. I appreciate your effort for fixing this and thanks in advance.

**Comment by pankajparkar** [comment] 2020-10-19 15:07
@cattlleya The issue is resolved in version 1.0.6. Please take an update and let me know if it works for you.

Working [ng-run demo](https://ng-run.com/edit/F1nkxZzSp88bEAQUfH8n)

![Screenshot 2020-10-19 at 11 07 14 PM](https://user-images.githubusercontent.com/5320044/96469480-d7675a80-125f-11eb-8322-59c7206580fd.png)

Once you confirm, I'll close the issue

**Comment by cattlleya** [comment] 2020-10-29 12:33
Hello @pankajparkar ,

Sorry for the late reply. I tried to update my package to version 1.0.6 but i have these errors. Would you know why  i am getting these errors? I am using Angular 9.

 
![image](https://user-images.githubusercontent.com/46396056/97574272-ef8c6600-1a25-11eb-9e8b-d1a6f5e0e675.png)

**Comment by pankajparkar** [comment] 2020-10-29 12:45
Can you please share a screenshot of package.json? And 
Output of `ng --version` command

**Comment by pankajparkar** [comment] 2020-11-24 14:18
@cattlleya I further investigated, and found that it works fine only when `enableIvy` option is enable in `tsconfig.json`, I'll add non ivy support (`ViewEngine`) to it.

**Comment by cattlleya** [comment] 2020-11-25 00:12
@pankajparkar , yes enableIvy option is not enable in my config due to compatibility issue of my other libraries. Thanks.

**Comment by pankajparkar** [comment] 2020-11-25 00:14
@cattlleya Thanks for confirmation 🙏, I'll try to fix it before end of this week.

**Comment by pankajparkar** [comment] 2023-04-09 08:59
@cattlleya Sorry for the very long delay to fix this issue.

v2.0.0 has addressed this issue

**Closed by pankajparkar** 2023-04-09 08:59 UTC
Labels: bug, p1
